spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/resto
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true
        temp:
          use_jdbc_metadata_defaults: false
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: 028ac0ec3b01279ee082267744f15fba3de0413dfc5767850f2583adf815c435

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web:
          socket: DEBUG
